const mmap = new Map([
  ['Chua xac dinh', 'Chua xac dinh'],
    ['LA1003', 'Anh văn 1'],
  ['PH1003', 'Vật lý 1'],
  ['MT1003', 'Giải tích 1'],
  ['CO1005', 'Nhập môn điện toán'],
  ['CO1023', 'Hệ thống số'],
  ['LA1005', 'Anh văn 2'],
  ['MT1005', 'Giải tích 2'],
  ['MT1007', 'Đại số tuyến tính'],
  ['CO1007', 'Kỹ thuật lập trình'],
  ['CO1027', 'Cấu trúc rời rạc cho khoa học máy tính'],
  ['PH1007', 'Thí nghiệm vật lý'],
  ['MI1003', 'Giáo dục quốc phòng'],
  ['LA1007', 'Anh văn 3'],
  ['SP1031', 'Triết học Mác - Lênin'],
  ['CO2007', 'Kiến trúc máy tính'],
  ['CO2011', 'Mô hình hóa toán học'],
  ['CO2003', 'Cấu trúc dữ liệu và giải thuật'],
  ['LA1009', 'Anh văn 4'],
  ['SP1033', 'Kinh tế chính trị Mác - Lênin'],
  ['CO2017', 'Hệ điều hành'],
  ['CO2014', 'TN Hệ cơ sở dữ liệu'],
  ['CO2039', 'Lập trình nâng cao'],
  ['MT2013', 'Xác suất và thống kê'],
  ['SP1035', 'Chủ nghĩa xã hội khoa học'],
  ['CO3093', 'Mạng máy tính'],
  ['CO2013', 'Hệ cơ sở dữ liệu'],
  ['CO3001', 'Công nghệ phần mềm'],
  ['CH1003', 'Hóa đại cương'],
  ['SP1039', 'Tư tưởng Hồ Chí Minh'],
  ['CO2001', 'Đồ án chuyên ngành'],
  ['CO3005', 'Đồ án tốt nghiệp'],
  ['CO3335', 'Thực tập tốt nghiệp'],
  ['SP1007', 'Pháp luật Việt Nam đại cương'],
  ['IM1013', 'Kinh tế học đại cương'],
  ['IM1023', 'Quản trị kinh doanh cho kỹ sư'],
  ['IM1025', 'Kinh tế kỹ thuật'],
  ['IM1027', 'Quản lý sản xuất cho kỹ sư'],
  ['IM3001', 'Quản lý dự án cho kỹ sư'],
  ['CO3011', 'Kiến trúc phần mềm'],
  ['CO3013', 'Kiểm tra phần mềm'],
  ['CO3015', 'Xây dựng chương trình dịch'],
  ['CO3017', 'Phân tích và thiết kế hệ thống'],
  ['CO3021', 'Hệ quản trị cơ sở dữ liệu'],
  ['CO3023', 'Cơ sở dữ liệu phân tán và hướng đối tượng'],
  ['CO3027', 'Thương mại điện tử'],
  ['CO3029', 'Khai phá dữ liệu'],
  ['CO3031', 'Phân tích và thiết kế giải thuật'],
  ['CO3033', 'Bảo mật hệ thống thông tin'],
  ['CO3035', 'Hệ thời gian thực'],
  ['CO3037', 'Phát triển ứng dụng internet of things'],
  ['CO3041', 'Hệ thống thông minh'],
  ['CO3043', 'Phát triển ứng dụng trên thiết bị di động'],
  ['CO3045', 'Lập trình game'],
  ['CO3047', 'Mạng máy tính nâng cao'],
  ['CO3049', 'Lập trình web'],
  ['CO3051', 'Hệ thống thiết bị di động'],
  ['CO3057', 'Xử lý ảnh số và thị giác máy tính'],
  ['CO3059', 'Đồ họa máy tính'],
  ['CO3061', 'Nhập môn trí tuệ nhân tạo'],
  ['CO3065', 'Công nghệ phần mềm nâng cao'],
  ['CO3067', 'Tính toán song song'],
  ['CO3069', 'Mật mã và an ninh mạng'],
  ['CO3071', 'Hệ phân bố'],
  ['CO3083', 'Mật mã học và mã hóa thông tin'],
  ['CO3085', 'Xử lý ngôn ngữ tự nhiên'],
  ['CO3089', 'Những chủ đề nâng cao trong khoa học máy tính'],
  ['CO3095', 'Phân tích dữ liệu lớn và trí tuệ kinh doanh'],
  ['CO3093', 'Mạng máy tính'],
  ['CO3101', 'Đồ án tổng hợp - hướng trí tuệ nhân tạo'],
  ['CO3103', 'Đồ án tổng hợp - hướng công nghệ phần mềm'],
  ['CO3105', 'Đồ án tổng hợp - hướng hệ thống thông tin'],
  ['CO3107', 'Đồ án tổng hợp - hướng kỹ thuật dữ liệu'],
  ['CO3109', 'Thực tập đồ án môn học đa ngành - hướng trí tuệ nhân tạo'],
  ['CO3111', 'Thực tập đồ án môn học đa ngành - hướng công nghệ phần mềm'],
  ['CO3115', 'Thực tập đồ án môn học đa ngành - hướng hệ thống thông tin'],
  ['CO3117', 'Thực tập đồ án môn học đa ngành - hướng kỹ thuật dữ liệu'],
  ['CO3127', 'Kỹ năng chuyên nghiệp cho kỹ sư'],
  ['CO4029', 'Đồ án chuyên ngành (cốt lõi tài năng)'],
  ['CO4031', 'Kho dữ liệu và hệ hỗ trợ quyết định'],
  ['CO4033', 'Hệ hoạch định tài nguyên tổ chức'],
  ['CO4035', 'Hệ thống thông tin quản lý'],
  ['CO4037', 'Bảo mật sinh trắc'],
  ['CO4039', 'Quản lý dự án phần mềm'],
  ['CO4337', 'Đồ án tốt nghiệp (Hệ cốt lõi tài năng)']
]);

module.exports = mmap